### ISSUE TITLE
Rate Limit Layer not Respected

### ISSUE THREAD

**Issue by cloud303-cholden** [tower-rs/tower#764]
Quick note: I created an issue in [axum](https://github.com/tokio-rs/axum/issues/2634) as well as this involves both tower and axum. I can close whichever of the two makes the most sense.

I am running into an issue with using the `RateLimitLayer` from `tower` with `axum`. I noticed that I can keep sending requests and the rate isn't actually limited. Below is a complete example.

```toml
[package]
name = "axum-rate-limit-test"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.4"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = { version = "1.0.108", features = ["std"] }
tokio = { version = "1.35.0", features = ["full"] }
tower = { version = "0.4.13", features = ["limit", "buffer"] }
```

```rust
use axum::{
    error_handling::HandleErrorLayer,
    http::StatusCode,
    routing::get,
    BoxError,
    Router,
    Json,
};
use serde::Serialize;
use tokio::net::TcpListener;
use tower::ServiceBuilder;

#[derive(Debug, Serialize)]
pub struct Health {
    pub ok: bool,
}

pub async fn health() -> Result<Json<Health>, (StatusCode, String)> {
    Ok(Json(Health { ok: true }))
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let app = Router::new()
        .route("/health", get(health))
        .route_layer(
            ServiceBuilder::new()
                .layer(HandleErrorLayer::new(|err: BoxError| async move {
                    (
                        StatusCode::INTERNAL_SERVER_ERROR,
                        format!("Unhandled error: {}", err),
                    )
                }))
                .buffer(1024)
                .rate_limit(1, tokio::time::Duration::from_secs(5))
        );
    let listener = TcpListener::bind("127.0.0.1:3000")
        .await
        .expect("failed to bind TCP listener");
    axum::serve(listener, app)
        .await
        .expect("failed to serve service");

    Ok(())
}
```

I expected the request rate to be limited to 1 per 5 seconds. But the below script executes without any rate limiting.

```bash
for n in {1..10}; do curl localhost:3000/health; done
```
